using System;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var children = Children.FromJson(jsonString);

namespace SNOMEDIDSelector.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Children
    {
        [JsonProperty("page")]
        public long Page { get; set; }

        [JsonProperty("pageCount")]
        public long PageCount { get; set; }

        [JsonProperty("totalCount")]
        public long TotalCount { get; set; }

        [JsonProperty("prevPage")]
        public object PrevPage { get; set; }

        [JsonProperty("nextPage")]
        public object NextPage { get; set; }

        [JsonProperty("links")]
        public Links Links { get; set; }

        [JsonProperty("collection")]
        public Collection[] Collection { get; set; }
    }
    public partial class Children
    {
        public static Children FromJson(string json) => JsonConvert.DeserializeObject<Children>(json, Misc.Converter.Settings);
    }
}