using System;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var children = Children.FromJson(jsonString);

namespace SNOMEDIDSelector.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Parents
    {
        [JsonProperty("prefLabel")]
        public string PrefLabel { get; set; }

        [JsonProperty("synonym")]
        public string[] Synonym { get; set; }

        [JsonProperty("definition")]
        public object[] Definition { get; set; }

        [JsonProperty("cui")]
        public string[] Cui { get; set; }

        [JsonProperty("semanticType")]
        public Uri[] SemanticType { get; set; }

        [JsonProperty("obsolete")]
        public bool Obsolete { get; set; }

        [JsonProperty("@id")]
        public Uri Id { get; set; }

        [JsonProperty("@type")]
        public Uri Type { get; set; }

        [JsonProperty("links")]
        public Links Links { get; set; }

        [JsonProperty("@context")]
        public Context Context { get; set; }
    }
    public partial class Parents
    {
        public static Parents[] FromJson(string json) => JsonConvert.DeserializeObject<Parents[]>(json, Misc.Converter.Settings);
    }
}